Don't be oververbose in send_email()
    ERROR: [pid 20172] Worker Worker(salt=640365789, workers=1, host=myhost.spotify.com, username=arash, pid=20172) failed    AppleIAPDailyCohortsLuigiQa(test=False)
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/luigi/worker.py", line 87, in run
        task_gen = self.task.run()
      File "/tmp/tmp9vkWs9/python/imported_luigi_tasks/in_app_purchases.py", line 123, in run
        raise Exception()
    Exception
    INFO: Sending warning email to 'dataex-squad+notifications@spotify.com'
    DEBUG: Emailing:
    -------------
    To: ('myhost@spotify.com',)
    From: luigi-client@myhost.spotify.com
    Subject: Luigi: MyTask() FAILED
    Message:
    Runtime error:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/luigi/worker.py", line 87, in run
        task_gen = self.task.run()
      File "/tmp/tmp9vkWs9/python/imported_luigi_tasks/in_app_purchases.py", line 123, in run
        raise Exception()
    Exception
    
    -------------

This is TOTALLY superflous information. Instead, I think we can just keep the
INFO line. The DEBUG line isn't useful even when debugging, because all of the
information is trivially retrieved anyway. Here's what I propose:


    ERROR: [pid 20172] Worker Worker(salt=640365789, workers=1, host=myhost.spotify.com, username=arash, pid=20172) failed    AppleIAPDailyCohortsLuigiQa(test=False)
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/luigi/worker.py", line 87, in run
        task_gen = self.task.run()
      File "/tmp/tmp9vkWs9/python/imported_luigi_tasks/in_app_purchases.py", line 123, in run
        raise Exception()
    Exception
    INFO: Sending warning email to 'dataex-squad+notifications@spotify.com'

This should be easier to read.

Former-commit-id: 3fb25c23d03ad5d763e7ff87dacef212817c0541