Embed six.py file for more compatibility
Currently, debian squeeze has a too old version of six in its repositories
(1.1, latest is 1.9).  For example there's no `add_metaclass`.  By embedding
six in the luigi package itself, we can ensure everyone uses the same version
of the library.

Previously I got this error which is now fixed. Nice that the six author put it
all in one file!

    $ nosetests test/date_hour_test.py
    E
    ======================================================================
    ERROR: Failure: AttributeError ('module' object has no attribute 'add_metaclass')
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python2.6/dist-packages/nose/loader.py", line 390, in loadTestsFromName
        addr.filename, addr.module)
      File "/usr/lib/python2.6/dist-packages/nose/importer.py", line 39, in importFromPath
        return self.importFromDir(dir_path, fqname)
      File "/usr/lib/python2.6/dist-packages/nose/importer.py", line 86, in importFromDir
        mod = load_module(part_fqname, fh, filename, desc)
      File "/spotify/home/arash/spotify/repos/luigis/github_luigi/test/date_hour_test.py", line 21, in <module>
        import luigi
      File "/spotify/home/arash/spotify/repos/luigis/github_luigi/luigi/__init__.py", line 21, in <module>
        from luigi import task
      File "/spotify/home/arash/spotify/repos/luigis/github_luigi/luigi/task.py", line 205, in <module>
        @six.add_metaclass(Register)
    AttributeError: 'module' object has no attribute 'add_metaclass'

    ----------------------------------------------------------------------
    Ran 1 test in 0.001s

    FAILED (errors=1)


Former-commit-id: bf53e4c56bbe47730332dd2ecbdcb108db6502c5